services:
  rompetomp_inertia.inertia:
    class: Rompetomp\InertiaBundle\Service\InertiaService
    public: false
    arguments:
      $engine: '@twig'
      $requestStack: '@request_stack'
      $container: '@service_container'
      $inertiaFormProcessorService: '@rompetomp_inertia.inertia_form_processor'
      $serializer: '@serializer'

  Rompetomp\InertiaBundle\Architecture\InertiaInterface: '@rompetomp_inertia.inertia'

  rompetomp_inertia.inertia_form_processor:
    class: Rompetomp\InertiaBundle\Service\InertiaFormProcessorService
    public: false

  rompetomp_inertia.inertia_error_response:
    class: Rompetomp\InertiaBundle\Architecture\DefaultInertiaErrorResponse
    public: false

  rompetomp_inertia.gateway:
    class: Rompetomp\InertiaBundle\Ssr\HttpGateway
    arguments:
      $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
      $inertia: '@rompetomp_inertia.inertia'

  Rompetomp\InertiaBundle\Architecture\GatewayInterface: '@rompetomp_inertia.gateway'

  rompetomp_inertia.twig_extension:
    class: Rompetomp\InertiaBundle\Twig\InertiaTwigExtension
    public: false
    arguments:
      $inertia: '@rompetomp_inertia.inertia'
      $gateway: '@rompetomp_inertia.gateway'
    tags:
      - { name: twig.extension }

  Rompetomp\InertiaBundle\EventListener\InertiaListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request }
      - { name: kernel.event_listener, event: kernel.response }
    arguments:
      $inertia: '@rompetomp_inertia.inertia'
      $csrfTokenManager: '@security.csrf.token_manager'
      $debug: '%kernel.debug%'
      $container: '@service_container'
      $defaultInertiaErrorResponse: '@rompetomp_inertia.inertia_error_response'

  Rompetomp\InertiaBundle\EventListener\InertiaResponseAttributeListener:
    tags:
      - { name: kernel.event_listener, event: kernel.view }
    arguments:
      $inertia: '@rompetomp_inertia.inertia'
