name: CI

on: [push, pull_request]

env:
  fail-fast: false

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      name: Configure npm caching
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/CI.yml') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Run prettier
      run: |-
        npx prettier --check
    
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.0', '8.1' , '8.2']

    name: Tests on PHP ${{ matrix.php-versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install dependencies
        run: composer install --ansi --no-progress

      - name: PHPUnit Tests
        run: vendor/bin/simple-phpunit
