name: CI

on: [push, pull_request]

env:
  fail-fast: false

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      - name: Prettify code
        uses: creyD/prettier_action@v4
        with:
          dry: True
          prettier_plugins: "@prettier/plugin-php"
          prettier_options: --config ./.prettierrc --check
          
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.0', '8.1' , '8.2']

    name: Tests on PHP ${{ matrix.php-versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install dependencies
        run: composer install --ansi --no-progress

      - name: PHPUnit Tests
        run: vendor/bin/simple-phpunit
